/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROJECT_DEFINITION = 1;
  /** RegularExpression Id. */
  int TASKS = 2;
  /** RegularExpression Id. */
  int TAKE = 3;
  /** RegularExpression Id. */
  int USER = 4;
  /** RegularExpression Id. */
  int PROJECT = 5;
  /** RegularExpression Id. */
  int GET_PROJECTS = 6;
  /** RegularExpression Id. */
  int GET_PROJECT = 7;
  /** RegularExpression Id. */
  int EXIT = 8;
  /** RegularExpression Id. */
  int LEAVE = 9;
  /** RegularExpression Id. */
  int REGISTER = 10;
  /** RegularExpression Id. */
  int YEAR = 11;
  /** RegularExpression Id. */
  int MONTH = 12;
  /** RegularExpression Id. */
  int DAY = 13;
  /** RegularExpression Id. */
  int DATE = 14;
  /** RegularExpression Id. */
  int HOUR = 15;
  /** RegularExpression Id. */
  int MINUTES = 16;
  /** RegularExpression Id. */
  int SECONDS = 17;
  /** RegularExpression Id. */
  int MILISECONDS = 18;
  /** RegularExpression Id. */
  int TIME = 19;
  /** RegularExpression Id. */
  int DATETIME = 20;
  /** RegularExpression Id. */
  int EOL = 21;
  /** RegularExpression Id. */
  int END = 22;
  /** RegularExpression Id. */
  int COLON = 23;
  /** RegularExpression Id. */
  int DIGIT = 24;
  /** RegularExpression Id. */
  int LETTER = 25;
  /** RegularExpression Id. */
  int VARIABLE = 26;
  /** RegularExpression Id. */
  int SPECIAL = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"PROJECT_DEFINITION\"",
    "\"TASKS\"",
    "\"TAKE\"",
    "\"USER\"",
    "\"PROJECT\"",
    "\"GET_PROJECTS\"",
    "\"GET_PROJECT\"",
    "\"EXIT\"",
    "\"LEAVE\"",
    "\"REGISTER\"",
    "<YEAR>",
    "<MONTH>",
    "<DAY>",
    "<DATE>",
    "<HOUR>",
    "<MINUTES>",
    "<SECONDS>",
    "<MILISECONDS>",
    "<TIME>",
    "<DATETIME>",
    "<EOL>",
    "\";\"",
    "\":\"",
    "<DIGIT>",
    "<LETTER>",
    "<VARIABLE>",
    "<SPECIAL>",
  };

}
