/* Parser.java */
/* Generated By:JavaCC: Do not edit this line. Parser.java */
import java.util.ArrayList;
import java.io.BufferedWriter;

public class Parser implements ParserConstants {
  static Database db = null;

  public static void main(String args[]) {
  }

  public void setDatabase(Database db) {
    this.db = db;
  }

  final public void parse(BufferedWriter writer, String ip, int port) throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case GET_PROJECT:{
        jj_consume_token(GET_PROJECT);
        jj_consume_token(END);
get_project(writer);
        break;
        }
      case PROJECT_DEFINITION:{
        jj_consume_token(PROJECT_DEFINITION);
        jj_consume_token(COLON);
project_definition(writer);
        break;
        }
      case TAKE:{
        jj_consume_token(TAKE);
        jj_consume_token(END);
take(writer, ip, port);
        break;
        }
      case GET_PROJECTS:{
        jj_consume_token(GET_PROJECTS);
get_projects(writer);
        break;
        }
      default:
        jj_la1[0] = jj_gen;
{if ("" != null) return;}
      }
      jj_consume_token(EOL);
parse(writer, ip, port);
    } catch (ParseException e) {
Token token=null;
        write(writer,"Fail;");
        do {
            token = getNextToken();
            write(writer,token.toString());
        } while (token.kind != EOL);
        write(writer,"\u005cn");
    }
  }

  final public void project_definition(BufferedWriter writer) throws ParseException {Token proj=null, tasks=null; boolean success=false;
    proj = jj_consume_token(VARIABLE);
    jj_consume_token(END);
    jj_consume_token(TASKS);
    jj_consume_token(COLON);
    tasks = jj_consume_token(DIGIT);
    jj_consume_token(END);
success = db.createProject(proj.toString());
        if (!success) {
            write(writer,"Fail;PROJECT_DEFINITION:"+proj.toString()+";\u005cn");
            {if ("" != null) return;}
        }
        write(writer,"OK;PROJECT_DEFINITION:" + proj.toString() +"\u005cn");
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VARIABLE:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      task(writer, proj);
    }
  }

  final public void task(BufferedWriter writer, Token proj) throws ParseException {Token task=null, start=null, end=null; boolean success=false;
    task = jj_consume_token(VARIABLE);
    jj_consume_token(END);
    start = jj_consume_token(DATETIME);
    jj_consume_token(END);
    end = jj_consume_token(DATETIME);
    jj_consume_token(END);
success = db.createTask(proj.toString(),
                                task.toString(),
                                start.toString(),
                                end.toString());
        if (!success) {
            write(writer,"Fail;"+task.toString() +
                         ":"+start.toString() +
                         ";"+end.toString() + ";\u005cn");
        }
  }

  final public void take(BufferedWriter writer, String ip, int port) throws ParseException {Token user=null, proj=null, task=null; boolean success=false;
    jj_consume_token(USER);
    jj_consume_token(COLON);
    user = jj_consume_token(VARIABLE);
    jj_consume_token(END);
    jj_consume_token(PROJECT);
    jj_consume_token(COLON);
    proj = jj_consume_token(VARIABLE);
    jj_consume_token(END);
    task = jj_consume_token(VARIABLE);
success = db.assignTask(proj.toString(), task.toString(), user.toString());
        if (success && ip != null) {
            success = db.updateUser(user.toString(), ip, port);
        }
        if (!success) {
            write(writer,"FAIL;TAKE;USER:"+user.toString()+
                         ";PROJECT"+proj+";"+task.toString());
            {if ("" != null) return;}
        }
        write(writer,"OK;TAKE;USER:"+user.toString()+
                     ";PROJECT:"+proj.toString()+";"+
                     task.toString() + "\u005cn");
  }

  final public void get_projects(BufferedWriter writer) throws ParseException {
ArrayList<String> projects = db.getProjects();
        if (projects == null) {
            write(writer, "FAIL;GET_PROJECTS;" + "\u005cn");
            {if ("" != null) return;}
        }
        write(writer, "OK;PROJECTS:"+projects.size());
        for (int i = 0; i < projects.size(); i++) {
            write(writer, ";" + projects.get(i));
        }
        write(writer, "\u005cn");
  }

  final public void get_project(BufferedWriter writer) throws ParseException {Token project=null;
    project = jj_consume_token(VARIABLE);
ArrayList<Task> tasks = db.getProject(project.toString());
        if (tasks == null) {
            write(writer, "FAIL;GET_PROJECT;" + project.toString() + "\u005cn");
            {if ("" != null) return;}
        }
        String buffer = "OK;PROJECT_DEFINITION:" + project.toString() +
                        ";TASKS:"+tasks.size()+";";

        for (int i = 0; i < tasks.size(); i++) {
            buffer += tasks.get(i).toString();
        }
        write(writer, buffer + "\u005cn");
  }

  final public void write(BufferedWriter writer, String msg) throws ParseException {
try {
            writer.write(msg);
            writer.flush();
        } catch (Exception e) {
            System.err.print("Failed to write: " + e.getMessage() + "\u005cn");
        }
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[2];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xca,0x1000000,};
   }

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[26];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 2; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 26; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
